In [2]:

import numpy as np

In [2]:
# 다음은 1부터 10까지 1차원 배열을 생성하고 배열의 속성을 알아보는 프로그램이다.
# 실행결과를 확인하고 빈칸에 가장 알맞은 속성을 작성하세요

arr = np.arange(1,11)
print(arr)
print('ndim:',arr.ndim)
print(arr.shape)
print(arr.dtype)
print('size:',arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
ndim: 1
(10,)
int64
size: 10


In [3]:
# 값이 10~50인 백터를 만들고 백터를 반전시켜 출력해 보세요
arr2 = np.arange(10,50)
arr2 = arr2[::-1]
arr2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [4]:
# 랜덤 값이 있는 10x10 배열을 만들고 최댓값과 최솟값을 찾아보세요
arr3 = np.random.rand(10, 10)
print(arr3.min())
print(arr3.max())


0.026141907584206092
0.986420895364453


In [5]:
# 0~8 범위의 값을 사용하여 3x3 배열을 생성해 보세요
arr4 = np.arange(0,9).reshape(3, 3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# 다음과 같이 1에서 24까지의 값을 가지는 4x6 크기의 2차원 행렬 arr을 생성해 보세요
arr5 = np.arange(1,25).reshape(4,6)
arr5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [7]:
# arr 배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성해 보세요
print(arr5[1:3,1:5])

[[ 8  9 10 11]
 [14 15 16 17]]


In [9]:
#arr 배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성해 보세요
print(arr5[2:,::-1])

[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]


In [13]:
# arr 배열에서 2의 배수만 출력해 보세요
arr5[arr5%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [14]:
# arr 배열에서 10부터 20까지의 값만 출력해 보세요
arr5[(arr5>=10) & (arr5<=20)]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
# numpy 배열을 사용하여 1부터 20까지의 연속된 정수값을 가지는 1차원 배열을 생성하여 실행결과와 같이 출력
arr = np.arange(1,21)
print(arr[-1])
print(arr.sum())
print(arr.mean())
new_arr = arr.reshape(5,4)
print(new_arr)


20
210
10.5
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [5]:
salary=[200,150,180,220,250]
new_salary=np.array(salary,dtype='float64') * 1.5
print('인상된 금액: ', new_salary)
avg_salary=np.mean(new_salary)
print("평균 금액: ",avg_salary)
result = new_salary >= avg_salary
print("평균이상인 원소: ", new_salary[result])
print("평균이상인 원소의 개수: ", len(new_salary[result]))

인상된 금액:  [300. 225. 270. 330. 375.]
평균 금액:  300.0
평균이상인 원소:  [300. 330. 375.]
평균이상인 원소의 개수:  3
